from enum import StrEnum


class ErrorCode(StrEnum):
    AUTH_INVALID_EMAIL = "AUTH_INVALID_EMAIL"
    AUTH_INVALID_PASSWORD = "AUTH_INVALID_PASSWORD"
    AUTH_EMAIL_ALREADY_REGISTERED = "AUTH_EMAIL_ALREADY_REGISTERED"
    AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS"
    AUTH_ACCESS_TOKEN_INVALID = "AUTH_ACCESS_TOKEN_INVALID"
    AUTH_REFRESH_TOKEN_INVALID = "AUTH_REFRESH_TOKEN_INVALID"
    AUTH_EMAIL_NOT_VERIFIED = "AUTH_EMAIL_NOT_VERIFIED"
    AUTH_ACCOUNT_DISABLED = "AUTH_ACCOUNT_DISABLED"

    USER_NOT_FOUND = "USER_NOT_FOUND"

    INTERNAL_ERROR = "INTERNAL_ERROR"
