[tool.poetry]
name = "auth-service"
version = "0.0.1"
description = "Vstavka auth-service"
authors = ["Роман <roma.korotaev2015@mail.ru>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
uuid6 = "^2025.0.1"
email-validator = "^2.3.0"
pwdlib = { extras = ["argon2"], version = "^0.3.1" }
pyjwt = "^2.14.0"
sqlalchemy = "^2.0.54"
aiosqlite = "^0.22.1"
pydantic-settings = "^2.15.0"
dependency-injector = "^4.49.1"
fastapi = "^0.141.1"
uvicorn = "^0.53.0"
colorlog = "^6.12.0"


[tool.poetry.group.test.dependencies]
pytest = "^9.1.1"
pytest-cov = "^7.1.0"
pytest-asyncio = "^1.4.0"
httpx = "^0.28.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
