"""Added account and session table

Revision ID: aa484214d022
Revises:
Create Date: 2026-09-21 21:20:00.747110

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'aa484214d022'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('public_id', sa.String(), nullable=False),
                    sa.Column('email', sa.String(length=255), nullable=False),
                    sa.Column('status', sa.Enum('ACTIVE', 'DISABLED', 'DELETED', name='account_status'),
                              nullable=False),
                    sa.Column('password_hash', sa.String(length=255), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_account_email'), 'account', ['email'], unique=True)
    op.create_index(op.f('ix_account_public_id'), 'account', ['public_id'], unique=True)
    op.create_table('session',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('public_id', sa.String(), nullable=False),
                    sa.Column('account_id', sa.Integer(), nullable=False),
                    sa.Column('refresh_token_hash', sa.String(length=64), nullable=False),
                    sa.Column('ip', sa.String(length=45), nullable=True),
                    sa.Column('user_agent', sa.String(length=512), nullable=True),
                    sa.Column('device_info', sa.String(length=255), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
                    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_session_account_id'), 'session', ['account_id'], unique=False)
    op.create_index(op.f('ix_session_public_id'), 'session', ['public_id'], unique=True)
    op.create_index(op.f('ix_session_refresh_token_hash'), 'session', ['refresh_token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_refresh_token_hash'), table_name='session')
    op.drop_index(op.f('ix_session_public_id'), table_name='session')
    op.drop_index(op.f('ix_session_account_id'), table_name='session')
    op.drop_table('session')
    op.drop_index(op.f('ix_account_public_id'), table_name='account')
    op.drop_index(op.f('ix_account_email'), table_name='account')
    op.drop_table('account')
    # ### end Alembic commands ###
